name: co2minus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  google_fonts: ^8.0.2
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans/MiSans-Regular.otf
        - asset: assets/fonts/MiSans/MiSans-Thin.otf
          weight: 100
        - asset: assets/fonts/MiSans/MiSans-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/MiSans/MiSans-Light.otf
          weight: 300
        - asset: assets/fonts/MiSans/MiSans-Normal.otf
          weight: 400
        - asset: assets/fonts/MiSans/MiSans-Medium.otf
          weight: 500
        - asset: assets/fonts/MiSans/MiSans-Demibold.otf
          weight: 600 # Or Semibold, you can choose which to map here
        - asset: assets/fonts/MiSans/MiSans-Bold.otf
          weight: 700
        - asset: assets/fonts/MiSans/MiSans-Heavy.otf
          weight: 800
