name: co2minus
description: "Track. Reduce. Neutralize."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  google_fonts: ^8.0.2
  camera: ^0.12.0
  google_sign_in: ^6.2.1
  health: ^11.0.0
  permission_handler: ^10.3.0
  shared_preferences: ^2.2.3
  google_mlkit_text_recognition: ^0.14.0
  tflite_flutter: ^0.11.0
  arcore_flutter_plugin: ^0.1.0
  fluttertoast: ^9.0.0
  image: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/flutter_lca_database.json
    - assets/flutter_scaler_config.json
    - assets/models/yolo.tflite
    - assets/models/gru.tflite
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans/MiSans-Regular.otf
        - asset: assets/fonts/MiSans/MiSans-Thin.otf
          weight: 100
        - asset: assets/fonts/MiSans/MiSans-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/MiSans/MiSans-Light.otf
          weight: 300
        - asset: assets/fonts/MiSans/MiSans-Normal.otf
          weight: 400
        - asset: assets/fonts/MiSans/MiSans-Medium.otf
          weight: 500
        - asset: assets/fonts/MiSans/MiSans-Demibold.otf
          weight: 600
        - asset: assets/fonts/MiSans/MiSans-Bold.otf
          weight: 700
        - asset: assets/fonts/MiSans/MiSans-Heavy.otf
          weight: 800
