// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8Xl1wEACNi9b-njB3k2uKY9Mk9aSH0U',
    appId: '1:935965368269:web:63d3ce4c686650f0676e84',
    messagingSenderId: '935965368269',
    projectId: 'co2-abvlnt',
    authDomain: 'co2-abvlnt.firebaseapp.com',
    storageBucket: 'co2-abvlnt.firebasestorage.app',
    measurementId: 'G-4XCBSMR3F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mkAr7Mjdefw49BUk07QxSAXWlQRiYc4',
    appId: '1:935965368269:android:bc409c7168966c62676e84',
    messagingSenderId: '935965368269',
    projectId: 'co2-abvlnt',
    storageBucket: 'co2-abvlnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEgJyLZHGtbrbdlFXbOPTNRr_vRKVW-gg',
    appId: '1:935965368269:ios:c90d65f6498003c1676e84',
    messagingSenderId: '935965368269',
    projectId: 'co2-abvlnt',
    storageBucket: 'co2-abvlnt.firebasestorage.app',
    androidClientId: '935965368269-dg3eccocg9d4iadkp9do50cvhrtssujk.apps.googleusercontent.com',
    iosClientId: '935965368269-s1cvfipt99mvbk9a1j44gi461o5gjoeq.apps.googleusercontent.com',
    iosBundleId: 'com.abvlnt.co2minus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEgJyLZHGtbrbdlFXbOPTNRr_vRKVW-gg',
    appId: '1:935965368269:ios:c90d65f6498003c1676e84',
    messagingSenderId: '935965368269',
    projectId: 'co2-abvlnt',
    storageBucket: 'co2-abvlnt.firebasestorage.app',
    androidClientId: '935965368269-dg3eccocg9d4iadkp9do50cvhrtssujk.apps.googleusercontent.com',
    iosClientId: '935965368269-s1cvfipt99mvbk9a1j44gi461o5gjoeq.apps.googleusercontent.com',
    iosBundleId: 'com.abvlnt.co2minus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ8Xl1wEACNi9b-njB3k2uKY9Mk9aSH0U',
    appId: '1:935965368269:web:208d38c8cd1f90f3676e84',
    messagingSenderId: '935965368269',
    projectId: 'co2-abvlnt',
    authDomain: 'co2-abvlnt.firebaseapp.com',
    storageBucket: 'co2-abvlnt.firebasestorage.app',
    measurementId: 'G-RJZMQ3X1MY',
  );

}